DROP TABLE IF EXISTS categories CASCADE;

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS categories
(
    category_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY UNIQUE,
    name        VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users
(
    user_id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY UNIQUE,
    name    VARCHAR(256) NOT NULL,
    email   VARCHAR(256) NOT NULL UNIQUE
);